### ISSUE TITLE
How to get each domain perplexity using your code?

### ISSUE THREAD

**Issue by zyh3826** [feiyang-k/AutoScale#1]
In `run_clm.py` line 649 compute the perplexity, how do we get each domain perplexity? I think this can only get all `val_data` perplexity

**Comment by feiyang-k** [comment]
Hi @zyh3826 , we added a helper script in /utils/ for calculating this per-domain perplexity. (Also, we merged run_clm.py into this directory). Hope it helps.

**Comment by zyh3826** [comment]
> Hi @zyh3826 , we added a helper script in /utils/ for calculating this per-domain perplexity. (Also, we merged run_clm.py into this directory). Hope it helps.

Hi @feiyang-k , thanks 
I have few questions

1. did you set the total samples as a constant during training? the paper mentioned.

2. in `DDO_example.ipnb` chapter `## (example) Fit power law function for PPL of one domain` this line:
`x = np.array([1/5, 1, 3])`
why not
`x = np.array([1/3, 1, 3])`
or normalized multipliers
`x = np.array([0.143, 0.333, 0.6])`
